### ISSUE TITLE
Interactive demo doesn't show up on Windows

### ISSUE THREAD

**Issue by mmattyg** [podgorskiy/ALAE#10]
Windows 10, Python 3.6, all the dependencies installed
`python interactive_demo.py`
Is working for a few seconds and then exiting with no visual result or prompt. Any ideas on how to debug?

**Comment by podgorskiy** [comment]
I don't have a windows machine at hand, but if you could provide some more details, that would be helpful.

You said that it works for a few seconds. Could you please step through it and figure out where exactly it crashes? Or at least before or after the image goes through the network?

Maybe, GPU has too small memory?

From what I understood, it does not printout anything, not a stack trace. It seems that it fails somewhere at C++ land. Could you please run the example from here https://github.com/podgorskiy/bimpy ?

**Comment by mmattyg** [comment]
I also suspected Bimpy, but the examples run well.
I'll try to install some debugger and step thru it. GPU has 8Gb (RTX 2070 Super)

**Comment by mmattyg** [comment]
Not 100% sure I know what I'm doing, but it seems to exit (with no prompt) at line 40 of launch.py
` torch.cuda.set_device(rank)`
[where rank=0]

**Comment by dennisbappert** [comment]
I can confirm that it works for me on Windows. (Anaconda, Python 3.7, latest Pytorch from conda, RTX 2060 Super - EGPU, Cuda 10.1)

**Comment by mmattyg** [comment]
Confirmed working as well!
I reset Windows (that was painful) and now working with Pytorch 1.5-cuda 10.2
