### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by bullgom** [podgorskiy/ALAE#14]
I'm sorry I know this is not a place for this but it is the only way I knew I how to contact.

In the [Paper](https://arxiv.org/abs/2004.04467) 
It is written "possible with SyleGAN alone," 2 lines above Acknowledgments.

Nice work BTW.

**Comment by podgorskiy** [comment]
Thank you for pointing that out!  I'll update arxiv version, but unfortunatelly I don't think that I'll be able to do somthing with camera ready version.
