### ISSUE TITLE
Async call to save_pic seems to cause some stability issue

### ISSUE THREAD

**Issue by eitanrich** [podgorskiy/ALAE#17]
train_alae.py seems to crash from time to time with the below error:

902it [04:31,  3.29it/s]Exception ignored in: <function Image.__del__ at 0x7ff8eb6549d8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Abort

As a workaround, I deleted the line @utils.async_func before def save_pic(x_rec) and this seems to solve the problem. It looks like some thread safety issue with the PIL Image destructor.
Update: I still got a crash with the workaround.

**Comment by podgorskiy** [comment]
I've experienced this crash from time to time too.
I have a guess, that it is somehow related to saving matplotlib figure

**Comment by eitanrich** [comment]
The problem seems to go away after changing (per [this](https://stackoverflow.com/questions/50848127/python-plot-image-save-error) answer) the matplotlib import in tracker.py to:

``import matplotlib``
``matplotlib.use('Agg')``

(I also tried cloning ``resultsample`` before calling ``save_pic()``, but I think the above did the trick).

BTW Very interesting work!!

**Comment by Mrwan1991** [comment]
@kuwawaadelia
