### ISSUE TITLE
no images on the screen

### ISSUE THREAD

**Issue by avrionov** [podgorskiy/ALAE#26]
I'm using GTX 970 on Windows 10. 

The UI is empty.  See the attached image

![image](https://user-images.githubusercontent.com/6868906/80854726-708db080-8bef-11ea-818b-da6cc8c06c5c.png)

**Comment by gencay** [comment]
The inner window is actually draggable. If you look at the right-bottom of the inner window you can resize.

Create a file in the root directory called `imgui.ini` with content:
```ini
[Window][Principal directions]
Pos=0,0
Size=1600,800
Collapsed=0
```

As you resize windows, this file will save the latest positions, width and height.

**Comment by avrionov** [comment]
Thanks. This fixed it.
