### ISSUE TITLE
Trying to train on Google CoLab

### ISSUE THREAD

**Issue by ayulockin** [podgorskiy/ALAE#28]
Hey, it's a super interesting paper and reading experience of the same was awesome. Really interesting work.

I am trying to replicate your work to get more insight. I tried training on Google CoLab, Here's the link to the notebook: https://colab.research.google.com/drive/14CpH6eU4XsHPN_y4lhfpEZGHPpXT0AxL

* The training script seem to take all the parameters from the config file.
* It's getting the name of the GPU.
* Load checkpoints.
* Start from epoch 157.
* Transition start but then it ends. 

![image](https://user-images.githubusercontent.com/31141479/80940648-0a2aad00-8dfe-11ea-9a78-87d9dc39495c.png)

I am not able to understand what's happening. In case I am doing something wrong do correct me. If I am not following the instructions properly do point me to the step I am missing. 

Thanks in advance :D

**Comment by Mrwan1991** [comment]
Fuck you

**Comment by udithhaputhanthri** [comment]
@ayulockin 
Hi, 
Did you solve that problem?  I have tried this by changing the config file and it still seems not working. Can you give me any missing points that you had?

Thanks
