### ISSUE TITLE
the missed lrmul item in Equalized Learning Rate Conv2d 

### ISSUE THREAD

**Issue by rardz** [podgorskiy/ALAE#32]
The Equalized LR [Conv2d](https://github.com/podgorskiy/ALAE/blob/master/lreq.py#L126) part seems inconsistent with the [Linear](https://github.com/podgorskiy/ALAE/blob/master/lreq.py#L68) part, with the scaling factor `lrmul` not included in Conv2d. I'm afraid you made a mistake here, however, things will be kepted unchange since in the default setting,  `lrmul` is `1.0` for every Conv2d module.

**Comment by podgorskiy** [comment]
Thank you! Fixed.
