### ISSUE TITLE
Training on Google CoLab

### ISSUE THREAD

**Issue by ayulockin** [podgorskiy/ALAE#36]
Hey, the paper is amazing. I really loved it. I am trying to recreate the MNIST experiment that you did. 
I only have Google CoLab as compute resource. 

I prepared mnist TFRecords using available `prepare_mnist_tfrecords.py`. The created `data` dir is in the root directory. 

When I try to train with `mnist_fc.yaml` as config file, training seems to start. But after showing this log nothing happens. 

![image](https://user-images.githubusercontent.com/31141479/81491150-26b86080-92a8-11ea-8ada-9a352ff72384.png)

I tried to debug the issue,
`batches = make_dataloader(cfg, logger, dataset, lod2batch.get_per_GPU_batch_size(), local_rank)`

After this line `print('debug')` is not printing debug. Inside `make_dataloader` function. The same is not happening after,
` batches = db.data_loader(iter(dataset), BatchCollator(local_rank), len(dataset) // GPU_batch_size)`

Am I not providing something to the training script? I have installed `dareblopy` in my runtime. 

To reproduce the experiment you can check out this [notebook](https://colab.research.google.com/drive/14CpH6eU4XsHPN_y4lhfpEZGHPpXT0AxL?usp=sharing).

What's happening? Any suggestion. 
Thank you.

**Comment by podgorskiy** [comment]
Sorry, for the late reply. Was very busy with graduation.

Please install the latest dareblopy. I did many fixes recently and made it more verbose, which might shed some light on the problem.

Never tried it in GoogleCoLab, so there are might be some nuances that I'm not aware of.

**Comment by ayulockin** [comment]
Thanks for the reply @podgorskiy. I will try the latest release of dareblopy. 

I co-authored a report(blog) with Sairam summarizing ALAE: https://wandb.ai/authors/alae/reports/Adversarial-Latent-Autoencoders--VmlldzoxNDA2MDY

Would love your feedbacks. :)
