### ISSUE TITLE
this is a bug ??

### ISSUE THREAD

**Issue by Johnson-yue** [podgorskiy/ALAE#42]
https://github.com/podgorskiy/ALAE/blob/5d8362f3ce468ece4d59982ff531d1b8a19e792d/net.py#L283

**Comment by leopolddavid** [comment]
I'm wondering too!
I get:

     self.from_rgb: nn.ModuleList[FromRGB] = nn.ModuleList()
                 ^
SyntaxError: invalid syntax

**Comment by leopolddavid** [comment]
I'm wondering too! I get:

    self.from_rgb: nn.ModuleList[FromRGB] = nn.ModuleList()
                 ^
SyntaxError: invalid syntax

**Comment by neverix** [comment]
[These are type hints](https://www.python.org/dev/peps/pep-0484/). Update Python to 3.6 or higher.

**Comment by Johnson-yue** [comment]
thank you ，I will try it
