### ISSUE TITLE
Which files to be used to run ALAE on permutation invariant MNIST?

### ISSUE THREAD

**Issue by ayulockin** [podgorskiy/ALAE#45]
I am trying to recreate the results from your permutation invariant MNIST section. Can you help me understand which all files should I use?

For example which file should I use between `train_alae.py` and `train_alae_separate.py`?
Similary between `model.py` and `model_separate.py`?

Thanks in advance @podgorskiy :)

**Comment by podgorskiy** [comment]
The master branch does not include configs for training permutation invariant MNIST.

What you are looking is in mnist_ref branch https://github.com/podgorskiy/ALAE/tree/mnist_ref
But that code is not cleaned up

*_separate - is for ablation study
