### ISSUE TITLE
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader! ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program!

### ISSUE THREAD

**Issue by hoenickf** [podgorskiy/ALAE#48]
When running the interactive demo I get:
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program!

**Comment by hoenickf** [comment]
The reason was that I ran it on a vm without graphics interface.

**Comment by rochakjain361** [comment]
This is working
