### ISSUE TITLE
VRAM

### ISSUE THREAD

**Issue by test1230-lab** [podgorskiy/ALAE#56]
How much vram is needed to train the 1024 from scratch?

**Comment by podgorskiy** [comment]
You can do it with 8 X GPUs with 16GB. The weight on google drive were obtained on such machine.

Though. having 8 X GPUs with 24GB is better, because you can keep batch size of 32 when at 1024x1024 resolution. With 8 X 16GB I had to set batchsize to 24 when at 1024x1024 resolution

**Comment by test1230-lab** [comment]
Thanks for the info
