### ISSUE TITLE
dareblopy aborted (core dump)

### ISSUE THREAD

**Issue by ewrfcas** [podgorskiy/ALAE#57]
https://github.com/podgorskiy/ALAE/blob/5d8362f3ce468ece4d59982ff531d1b8a19e792d/dataloader.py#L129
aborted (core dump) error in this line

**Comment by udithhaputhanthri** [comment]
Hi @ewrfcas, I was trying to train ALAE on Google colab and the training has stopped. The error is coming from the above line. The kernel is shutting down when calling that line. How did you solve that issue?

**Comment by astroartisan** [comment]
Same issue
