### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by youngAt19** [podgorskiy/ALAE#60]
How long did it take to train the style_alae 1024

**Comment by podgorskiy** [comment]
It takes a slightly over two days to reach 512x512 and slightly over two days to reach 1024x1024 on a machine with 8 X Titan RTX

The original model wieghts that can be found on google drive (that were trained before the CVPR submition), were obtained on much smaller hardware. The FFHQ 1024 model was trained on a machine  with 4 X Titan X up untill it reached 512x512 (took over 10 days), and then 2 days on AWS machine with 8 V100. All other weight were trained on 4 X Titan X only.

**Comment by youngAt19** [comment]
thanks!
