### ISSUE TITLE
dlutils doesn't work to get the pretrained weights : you've hit your quotas

### ISSUE THREAD

**Issue by ilnmtlbnm** [podgorskiy/ALAE#9]
You've reached a quota on your files, and dlutils doesn't throw an error.
Not really an issue with ALAE.

There's an easy fix : one can download the pretrained weights manually here : https://drive.google.com/drive/folders/1iZodDA4q1IKRRgV2nJuAyyuCwQGtL4vp?usp=sharing

**Comment by podgorskiy** [comment]
Thanks for letting me know about the problem.
Now dlutils throws an error.
I also duplicated all data on S3. Let me know how everything is working.
